name: Update panna poren

on: 
  push:
    branches:
      - main

jobs:
    update_doing:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Docker Login
              uses: docker/login-action@v3.1.0
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GH_PAT }}
          
            - name: Build and push Docker images
              uses: docker/build-push-action@v5.3.0
              with:
                push: true
                tags: ghcr.io/${{ github.actor }}/app:latest
            
